const express=require("express"),cors=require("cors"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),path=require("path"),helmet=require("helmet"),rateLimit=require("express-rate-limit"),mongoose=require("mongoose");
const app=express(),PORT=process.env.PORT||3000;
const ADMIN_USER=process.env.ADMIN_USER||"isaias_admin",ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"troque123",JWT_SECRET=process.env.JWT_SECRET||"troque_esse_segredo",GOOGLE_CLIENT_ID=process.env.GOOGLE_CLIENT_ID||"660996534145-e2q8aq49f9ch1ll9i2u3chijkqplgb5g.apps.googleusercontent.com",MONGO_URI=process.env.MONGO_URI;
if(!MONGO_URI){console.error("MONGO_URI não configurado");process.exit(1)}
app.set("trust proxy",1);app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false}));app.use(cors());app.use(express.json({limit:"100kb"}));app.use(express.static(path.join(__dirname,"public")));
app.use("/api",rateLimit({windowMs:60000,limit:180,standardHeaders:true,legacyHeaders:false,message:{error:"Muitas requisições. Tente novamente em instantes."}}));
const loginLimiter=rateLimit({windowMs:10*60*1000,limit:5,standardHeaders:true,legacyHeaders:false,message:{error:"Muitas tentativas. Aguarde alguns minutos e tente novamente."}});
mongoose.connect(MONGO_URI).then(()=>console.log("MongoDB conectado")).catch(e=>{console.error("MongoDB erro:",e.message);process.exit(1)});
const User=mongoose.model("User",new mongoose.Schema({name:String,username:{type:String,unique:true,sparse:true},email:{type:String,unique:true,sparse:true},password:String,role:{type:String,default:"cliente"},provider:{type:String,default:"local"},picture:String,createdAt:{type:Date,default:Date.now}}));
const Product=mongoose.model("Product",new mongoose.Schema({name:String,price:String,image:String,link:String,category:String,offer:{type:Boolean,default:false},active:{type:Boolean,default:true},clicks:{type:Number,default:0},createdAt:{type:Date,default:Date.now}}));
const Click=mongoose.model("Click",new mongoose.Schema({productId:String,productName:String,category:String,userRole:String,createdAt:{type:Date,default:Date.now}}));
const Setting=mongoose.model("Setting",new mongoose.Schema({key:{type:String,unique:true},value:mongoose.Schema.Types.Mixed}));
const DEFAULT_CATEGORIES=["Casa","Eletrônicos","Esportes","Moda","Ofertas"];
async function init(){if(!await Setting.findOne({key:"storeOpen"}))await Setting.create({key:"storeOpen",value:true});if(!await Setting.findOne({key:"categories"}))await Setting.create({key:"categories",value:DEFAULT_CATEGORIES});if(await Product.countDocuments()===0)await Product.create([{name:"Produto em oferta Shopee",price:"29,90",image:"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=800",link:"https://shopee.com.br",category:"Ofertas",offer:true,active:true},{name:"Eletrônico exemplo",price:"59,90",image:"https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800",link:"https://shopee.com.br",category:"Eletrônicos",offer:false,active:true}])}init();
const clean=(t,m=700)=>typeof t==="string"?t.trim().slice(0,m):"",err=(res,s,m)=>res.status(s).json({error:m});
function auth(req,res,next){const token=(req.headers.authorization||"").replace("Bearer ","");if(!token)return err(res,401,"Entre na sua conta novamente.");try{req.user=jwt.verify(token,JWT_SECRET);next()}catch{return err(res,401,"Sessão expirada. Entre novamente.")}}
function optionalAuth(req,res,next){const token=(req.headers.authorization||"").replace("Bearer ","");try{req.user=token?jwt.verify(token,JWT_SECRET):{role:"visitante"}}catch{req.user={role:"visitante"}}next()}
function admin(req,res,next){if(!req.user||req.user.role!=="admin")return err(res,403,"Acesso não permitido.");next()}
async function storeOpen(){const s=await Setting.findOne({key:"storeOpen"});return s?!!s.value:true}
async function cats(){const s=await Setting.findOne({key:"categories"});return s?s.value:DEFAULT_CATEGORIES}
async function verifyGoogle(credential){const r=await fetch("https://oauth2.googleapis.com/tokeninfo?id_token="+credential);if(!r.ok)return null;const d=await r.json();return d.aud===GOOGLE_CLIENT_ID&&d.email_verified?d:null}
app.post("/api/google-login",loginLimiter,async(req,res)=>{try{const g=await verifyGoogle(clean(req.body.credential,5000));if(!g)return err(res,401,"Não foi possível confirmar sua conta Google.");let u=await User.findOne({provider:"google",email:g.email});if(!u)u=await User.create({name:g.name||g.email,username:g.email,email:g.email,picture:g.picture||"",password:"",role:"cliente",provider:"google"});const token=jwt.sign({id:u._id,username:u.username,name:u.name,role:u.role},JWT_SECRET,{expiresIn:"7d"});res.json({token,role:u.role,username:u.username,name:u.name})}catch{return err(res,500,"Não foi possível entrar com Google.")}});
app.post("/api/register",async(req,res)=>{try{const name=clean(req.body.name,80),username=clean(req.body.username,60).toLowerCase(),password=String(req.body.password||""),confirmPassword=String(req.body.confirmPassword||"");if(!name||!username||!password||!confirmPassword)return err(res,400,"Preencha tudo.");if(!/^[a-zA-Z0-9._-]{3,60}$/.test(username))return err(res,400,"Usuário inválido.");if(password!==confirmPassword)return err(res,400,"As senhas não conferem.");if(password.length<6)return err(res,400,"Senha com mínimo de 6 caracteres.");if(await User.findOne({username}))return err(res,400,"Usuário já existe.");await User.create({name,username,password:await bcrypt.hash(password,12),role:"cliente",provider:"local"});res.json({ok:true})}catch{return err(res,500,"Não foi possível criar a conta.")}});
app.post("/api/login",loginLimiter,async(req,res)=>{try{const username=clean(req.body.username,80).toLowerCase(),password=String(req.body.password||"");if(username===ADMIN_USER.toLowerCase()&&password===ADMIN_PASSWORD){const token=jwt.sign({username:ADMIN_USER,name:"Admin",role:"admin"},JWT_SECRET,{expiresIn:"7d"});return res.json({token,role:"admin",username:ADMIN_USER,name:"Admin"})}const u=await User.findOne({username});if(!u||u.provider==="google"||!await bcrypt.compare(password,u.password))return err(res,401,"Login inválido.");const token=jwt.sign({id:u._id,username:u.username,name:u.name,role:u.role},JWT_SECRET,{expiresIn:"7d"});res.json({token,role:u.role,username:u.username,name:u.name})}catch{return err(res,500,"Não foi possível entrar.")}});
app.post("/api/forgot-password",async(req,res)=>res.json({ok:true,message:"Se essa conta existir, enviaremos instruções de recuperação."}));
app.get("/api/store",async(req,res)=>res.json({storeOpen:await storeOpen(),categories:await cats(),paymentMode:"shopee_affiliate_now_future_payment_ready"}));
app.get("/api/products",auth,async(req,res)=>res.json({products:await Product.find({active:true}).sort({offer:-1,createdAt:-1}).lean(),storeOpen:await storeOpen(),categories:await cats()}));
app.get("/api/public-offers",async(req,res)=>res.json({products:await Product.find({active:true,offer:true}).sort({createdAt:-1}).lean(),storeOpen:await storeOpen(),categories:await cats()}));
app.get("/api/admin/dashboard",auth,admin,async(req,res)=>{const products=await Product.find().lean(),totalClicks=products.reduce((s,p)=>s+(p.clicks||0),0),topProducts=[...products].sort((a,b)=>(b.clicks||0)-(a.clicks||0)).slice(0,5),recentClicks=await Click.find().sort({createdAt:-1}).limit(8).lean();res.json({totalProducts:await Product.countDocuments(),totalUsers:await User.countDocuments(),totalClicks,storeOpen:await storeOpen(),topProducts,recentClicks,categories:await cats()})});
app.post("/api/products",auth,admin,async(req,res)=>{try{const name=clean(req.body.name,100),price=clean(req.body.price,30),image=clean(req.body.image),link=clean(req.body.link),category=clean(req.body.category,50)||"Ofertas",offer=!!req.body.offer;if(!name||!price||!image||!link)return err(res,400,"Preencha nome, preço, imagem e link.");await Product.create({name,price,image,link,category,offer,active:true,clicks:0});res.json({ok:true})}catch{return err(res,500,"Não foi possível adicionar produto.")}});
app.put("/api/products/:id",auth,admin,async(req,res)=>{try{await Product.findByIdAndUpdate(req.params.id,{name:clean(req.body.name,100),price:clean(req.body.price,30),image:clean(req.body.image),link:clean(req.body.link),category:clean(req.body.category,50),offer:!!req.body.offer,active:req.body.active!==false});res.json({ok:true})}catch{return err(res,500,"Não foi possível editar produto.")}});
app.delete("/api/products/:id",auth,admin,async(req,res)=>{try{await Product.findByIdAndDelete(req.params.id);res.json({ok:true})}catch{return err(res,500,"Não foi possível excluir produto.")}});
app.post("/api/admin/store-open",auth,admin,async(req,res)=>{const open=!!req.body.open;await Setting.findOneAndUpdate({key:"storeOpen"},{value:open},{upsert:true});res.json({ok:true,storeOpen:open})});
app.post("/api/admin/categories",auth,admin,async(req,res)=>{const categories=Array.isArray(req.body.categories)?req.body.categories.map(c=>clean(c,40)).filter(Boolean).slice(0,12):DEFAULT_CATEGORIES;await Setting.findOneAndUpdate({key:"categories"},{value:categories},{upsert:true});res.json({ok:true,categories})});
app.post("/api/products/:id/click",optionalAuth,async(req,res)=>{try{const p=await Product.findById(req.params.id);if(!p)return err(res,404,"Produto não encontrado.");p.clicks=(p.clicks||0)+1;await p.save();await Click.create({productId:String(p._id),productName:p.name,category:p.category,userRole:req.user?.role||"visitante"});res.json({ok:true,link:p.link})}catch{return err(res,500,"Não foi possível abrir produto.")}});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log(`IsaiasStore V4 rodando na porta ${PORT}`));
